---
title: "Stat 151a Project"
author: "Kelly Trinh, Hanfei Sun, and Nathan Lam"
output: pdf_document
---

https://www.rdocumentation.org/packages/fivethirtyeight/versions/0.6.1/topics/college_recent_grads


```{r Libraries, message=FALSE, warning=FALSE}
library(fivethirtyeight) #source of data
library(corrplot) #correlation plot
library(dplyr) #data frame manipulation
library(ggplot2) #plotting
library(leaps)#variable selection: adjr2, bic, cp
library(olsrr)#variable selection: aic, p-val
library(fastDummies)
library(faraway)
library(caret)
```

```{r}
crg <- college_recent_grads
cont <- select_if(crg, is.numeric)
cont["college_job_prop"] <- cont$college_jobs / (cont$college_jobs + cont$non_college_jobs)
cont["full_time_yearround_prop"] <- cont$employed_fulltime_yearround / cont$employed
cont <- na.omit(cont)
corrplot(cor(cont), type = "upper", order = "AOE")
crg["log_median"] <- log(crg$median)
crg["college_job_prop"] <- crg$college_jobs / (crg$college_jobs + crg$non_college_jobs)
crg["full_time_yearround_prop"] <- crg$employed_fulltime_yearround / crg$employed
crg <- na.omit(crg)



crg <- dummy_cols(crg, select_columns = "major_category", remove_selected_col = TRUE,remove_first_dummy = TRUE)
column_names <- make.names(names(crg),unique=TRUE)
colnames(crg) <- column_names


set.seed(11)
#randomly take 2:8 of data for training
training_size <- sample(dim(crg)[1],nrow(crg)*0.8)
training_data <- crg[training_size,]
testing_data <- crg[-training_size,]


```

```{r}
ggplot(aes(x = major_category, y = log_median), data = training_data) + geom_boxplot() + coord_flip()
```

```{r Variable Selection}
Y <- as.matrix(training_data$log_median)

X <- as.matrix(subset(training_data,select=-c(log_median,median, major_code, p25th, p75th, major)))
# Check for linear dependencies, remove "men" or "total"
alias(lm(Y~X))
X <- as.matrix(subset(training_data,select=-c(log_median,median, major_code, p25th, p75th, major, men)))
```

```{r}
#Forward Selection
model <- regsubsets(x = X, y = Y, method = "forward", nbest = 1) %>% summary()

adjustr2 <- model$adjr2
BIC <- model$bic
mallow_Cp <- model$cp


cbind(model$which[which.max(adjustr2),], model$which[which.min(BIC),],model$which[which.min(mallow_Cp),])


###################
#Backward Selection

model <- regsubsets(x = X, y = Y, method = "backward", nbest = 1) %>% summary()


adjustr2 <- model$adjr2
BIC <- model$bic
mallow_Cp <- model$cp
cbind(model$which[which.max(adjustr2),], model$which[which.min(BIC),],model$which[which.min(mallow_Cp),])

```

### Cross Validation

```{r}
# Backward Adjusted R-squared CV
tc <- trainControl(method = "LOOCV")
b_adjr2_mod_cv <- train(log_median ~ total + sample_size + sharewomen + 
                          employed + college_job_prop +
                          major_category_Biology...Life.Science+
                          major_category_Computers...Mathematics + 
                          major_category_Physical.Sciences, 
                          data = training_data, method = "lm",trControl = tc)
b_adjr2_mod_cv$results["RMSE"]
```


```{r}
# Backward BIC CV
b_bic_mod_cv <- train(log_median ~ rank + sharewomen + college_job_prop +  
                      major_category_Computers...Mathematics, 
                     data = training_data , 
                     method = "lm", trControl = tc)
  
b_bic_mod_cv$results["RMSE"]
```

```{r}
# Backward Mallow's Cp CV
b_cp_mod_cv <- train(log_median ~ rank + sharewomen + college_job_prop +  
                       major_category_Biology...Life.Science + 
                       major_category_Computers...Mathematics, 
                     data = training_data, method = "lm", trControl = tc)
b_cp_mod_cv$results["RMSE"]
```


```{r}
# Forward Adjusted R-squared CV
f_adjr2_model_cv <- train(log_median ~ rank + sharewomen + 
                           college_job_prop + major_category_Arts + 
                           major_category_Computers...Mathematics + 
                           major_category_Engineering  + 
                           major_category_Humanities...Liberal.Arts  + 
                           major_category_Industrial.Arts...Consumer.Services , 
                           data = training_data, method = "lm", trControl = tc)

f_adjr2_model_cv$results["RMSE"]

# Forward BIC CV
f_BIC_model_cv <- train(log_median ~ rank + college_job_prop + 
                           major_category_Engineering, 
                       data = training_data, method = "lm", trControl = tc)

f_BIC_model_cv$results["RMSE"]

# Forward Mallow's Cp CV
f_Cp_model_cv <- train(log_median ~ rank + college_job_prop + 
                         major_category_Arts + 
                         major_category_Engineering + 
                         major_category_Humanities...Liberal.Arts + 
                         major_category_Industrial.Arts...Consumer.Services, 
                      data = training_data, method = "lm", trControl = tc)

f_Cp_model_cv$results["RMSE"]






```


```{r}
#checking for overfitting

adjr2_model <- lm(log_median ~ rank + sharewomen + 
                           college_job_prop + major_category_Arts + 
                           major_category_Computers...Mathematics + 
                           major_category_Engineering  + 
                           major_category_Humanities...Liberal.Arts  + 
                           major_category_Industrial.Arts...Consumer.Services , 
                           data = training_data)

f_Cp_model <- lm(log_median ~ rank + college_job_prop + 
                         major_category_Arts + 
                         major_category_Engineering + 
                         major_category_Humanities...Liberal.Arts + 
                         major_category_Industrial.Arts...Consumer.Services, 
                         data = training_data)

f_adjr2_model_predict <- predict(adjr2_model, newdata = testing_data, type = "response")
sum((testing_data$log_median-f_adjr2_model_predict)^2)
cor(f_adjr2_model_predict, testing_data$log_median)**2

f_Cp_model_predict <- predict(f_Cp_model, newdata = testing_data, type = "response")
sum((testing_data$log_median-f_Cp_model_predict)^2)
cor(f_Cp_model_predict, testing_data$log_median)**2


```

```{r}
#interactions

model <- lm(log_median ~ rank + unemployment_rate + 
                          college_job_prop + major_category_Arts + 
                         major_category_Engineering + 
                         major_category_Humanities...Liberal.Arts, 
                      data = training_data)
model1 <- lm(log_median ~ rank + unemployment_rate + 
                          college_job_prop + major_category_Arts + 
                         major_category_Engineering + 
                         major_category_Humanities...Liberal.Arts + 
                         college_job_prop*major_category_Arts, 
                      data = training_data)
model2 <- lm(log_median ~ rank + unemployment_rate + 
                          college_job_prop + major_category_Arts + 
                         major_category_Engineering + 
                         major_category_Humanities...Liberal.Arts + 
                         college_job_prop*major_category_Arts + 
                         college_job_prop*major_category_Engineering, 
                      data = training_data)

model3 <- lm(log_median ~ rank + unemployment_rate + 
                          college_job_prop + major_category_Arts + 
                         major_category_Engineering + 
                         major_category_Humanities...Liberal.Arts + 
                         college_job_prop*major_category_Arts + 
                         college_job_prop*major_category_Engineering + 
                   college_job_prop*major_category_Humanities...Liberal.Arts, 
                      data = training_data)

anova(model, model1, model2, model3)

```






